// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCmy4HKp-qQRFnK0ng4jlJaah-BgiKH4PY',
//     appId: '1:779271581799:android:8b6193bad34c011d4924c2',
//     messagingSenderId: '779271581799',
//     projectId: 'javohir-d651d',
//     storageBucket: 'javohir-d651d.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBV1ZszPimvstA4ryapUr3cJ9DZE0NEAQM',
//     appId: '1:779271581799:ios:3ea16370130920224924c2',
//     messagingSenderId: '779271581799',
//     projectId: 'javohir-d651d',
//     storageBucket: 'javohir-d651d.appspot.com',
//     iosClientId: '779271581799-iildb0uamifl6u0l35c58brc9fdrdbc7.apps.googleusercontent.com',
//     iosBundleId: 'com.example.javohir',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBV1ZszPimvstA4ryapUr3cJ9DZE0NEAQM',
//     appId: '1:779271581799:ios:3ea16370130920224924c2',
//     messagingSenderId: '779271581799',
//     projectId: 'javohir-d651d',
//     storageBucket: 'javohir-d651d.appspot.com',
//     iosClientId: '779271581799-iildb0uamifl6u0l35c58brc9fdrdbc7.apps.googleusercontent.com',
//     iosBundleId: 'com.example.javohir',
//   );
// }
